# Generated by Django 6.0.6 on 2026-06-18 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="branch",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="branch",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="branch",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="branch",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="branch",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="branch",
            name="homepage_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="branch",
            name="image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="branch",
            name="is_flagship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="branch",
            name="location",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="branch",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="monthly_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="branch",
            name="opening_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="operating_hours",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="branch",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="branch",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="branch",
            name="revenue_trend",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="branch",
            name="show_on_homepage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="branch",
            name="staff_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="branch",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("maintenance", "Maintenance"),
                    ("opening_soon", "Opening Soon"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="branch",
            name="weekdays_hours",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="branch",
            name="weekend_hours",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["is_active", "display_order", "id"],
                name="idx_branch_active_order",
            ),
        ),
    ]
