[mypy]
python_version = 3.14
ignore_missing_imports = True
disable_error_code = import-untyped
warn_unused_ignores = True
exclude = (?x)(.*/migrations/.*|.*/tests/.*|conftest\.py)

[mypy-django.*]
ignore_missing_imports = True

[mypy-django_tenants.*]
ignore_missing_imports = True

[mypy-rest_framework.*]
ignore_missing_imports = True

[mypy-rest_framework_simplejwt.*]
ignore_missing_imports = True

[mypy-corsheaders.*]
ignore_missing_imports = True

[mypy-drf_spectacular.*]
ignore_missing_imports = True
