[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
pythonpath = .
addopts = --import-mode=importlib
testpaths = shared/tests apps/tenancy/tests apps/access/tests apps/branch/tests apps/inventory/tests config/tests
filterwarnings =
    ignore:'_UnionGenericAlias' is deprecated:DeprecationWarning:drf_spectacular.plumbing
