"""Platform-level module keys for platform RBAC."""

PLATFORM_MODULE_TENANTS = "platform.tenants"
PLATFORM_MODULE_FEATURES = "platform.features"
PLATFORM_MODULE_AUDIT_LOGS = "platform.audit_logs"
PLATFORM_MODULE_PLATFORM_USERS = "platform.platform_users"
PLATFORM_MODULE_SETTINGS = "platform.settings"
PLATFORM_MODULE_BILLING = "platform.billing"
PLATFORM_MODULE_PACKAGES = "platform.packages"

PLATFORM_MODULES = {
    PLATFORM_MODULE_TENANTS: "Tenants",
    PLATFORM_MODULE_FEATURES: "Feature Registry",
    PLATFORM_MODULE_AUDIT_LOGS: "Audit Logs",
    PLATFORM_MODULE_PLATFORM_USERS: "Platform Users",
    PLATFORM_MODULE_SETTINGS: "Settings",
    PLATFORM_MODULE_BILLING: "Billing",
    PLATFORM_MODULE_PACKAGES: "Packages",
}

PLATFORM_MODULE_KEYS = list(PLATFORM_MODULES.keys())

PLATFORM_ROLE_SUPERADMIN = "superadmin"
PLATFORM_ROLE_PLATFORM_MANAGER = "platform_manager"
PLATFORM_ROLE_SUPPORT_AGENT = "support_agent"

PREDEFINED_PLATFORM_ROLE_PERMISSIONS = {
    PLATFORM_ROLE_SUPERADMIN: {key: "full" for key in PLATFORM_MODULE_KEYS},
    PLATFORM_ROLE_PLATFORM_MANAGER: {
        PLATFORM_MODULE_TENANTS: "full",
        PLATFORM_MODULE_FEATURES: "view",
        PLATFORM_MODULE_AUDIT_LOGS: "view",
        PLATFORM_MODULE_PLATFORM_USERS: "view",
        PLATFORM_MODULE_SETTINGS: "view",
        PLATFORM_MODULE_BILLING: "view",
        PLATFORM_MODULE_PACKAGES: "view",
    },
    PLATFORM_ROLE_SUPPORT_AGENT: {
        PLATFORM_MODULE_TENANTS: "view",
        PLATFORM_MODULE_FEATURES: "none",
        PLATFORM_MODULE_AUDIT_LOGS: "view",
        PLATFORM_MODULE_PLATFORM_USERS: "none",
        PLATFORM_MODULE_SETTINGS: "none",
    },
}
