"""Generate subscription invoice PDFs."""

from __future__ import annotations

from io import BytesIO

from django.utils import timezone


def render_subscription_invoice_pdf(invoice, *, generated_by: str = "System") -> bytes:
    """Build a simple branded PDF for a TenantSubscriptionInvoice."""
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas

    from apps.billing.models import TenantSubscriptionInvoice

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    left = 50
    y = height - 60

    def draw_line(text: str, *, size: int = 10, bold: bool = False) -> None:
        nonlocal y
        font = "Helvetica-Bold" if bold else "Helvetica"
        pdf.setFont(font, size)
        pdf.drawString(left, y, str(text)[:120])
        y -= size + 10

    tenant_name = invoice.tenant.name if invoice.tenant_id else "-"
    invoice_ref = f"SUB-{str(invoice.id).replace('-', '')[:8].upper()}"
    package_label = invoice.package_slug or "-"
    amount_str = f"{invoice.currency} {invoice.amount:,.2f}"
    created_at = timezone.localtime(invoice.created_at).strftime("%d %b %Y, %I:%M %p")
    status_label = dict(TenantSubscriptionInvoice.STATUS_CHOICES).get(
        invoice.status, invoice.status.title()
    )

    def fmt_dt(value):
        if not value:
            return "-"
        return timezone.localtime(value).strftime("%d %b %Y")

    period = f"{fmt_dt(invoice.period_start)} – {fmt_dt(invoice.period_end)}"

    pdf.setFillColorRGB(0.1, 0.1, 0.1)
    draw_line("Sortorium", size=18, bold=True)
    draw_line("Subscription Invoice", size=14, bold=True)
    draw_line(f"Tenant: {tenant_name}", bold=True)
    draw_line(f"Invoice Ref: {invoice_ref}")
    draw_line(f"Transaction ID: {invoice.tran_id}")
    draw_line(f"Created: {created_at}")
    draw_line(f"Generated by: {generated_by or 'System'}")
    y -= 10
    draw_line("Invoice Details", size=12, bold=True)
    draw_line(f"Package: {package_label}")
    draw_line(f"Billing cycle: {invoice.billing_cycle}")
    draw_line(f"Period: {period}")
    draw_line(f"Gateway: {invoice.gateway_slug or '-'}")
    draw_line(f"Status: {status_label}", bold=True)
    draw_line(f"Amount: {amount_str}", size=12, bold=True)
    pdf.setFillColorRGB(0.4, 0.4, 0.4)
    pdf.setFont("Helvetica", 9)
    pdf.drawCentredString(
        width / 2,
        30,
        "System-generated subscription invoice. Thank you for choosing Sortorium.",
    )
    pdf.showPage()
    pdf.save()
    return buffer.getvalue()
