# Generated by Django 6.0.6 on 2026-06-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_rename_productcategory_softwareproductcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="softwareproductcategory",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "software product category",
                "verbose_name_plural": "software product categories",
            },
        ),
    ]
