# Generated by Django 6.0.6 on 2026-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_tenant_created_by_tenant_landing_page_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("verification", "Verification"),
                    ("invitation", "Invitation"),
                    ("password_reset", "Password Reset"),
                    ("platform_invite", "Platform Team Invitation"),
                    ("employee_invite", "Tenant Employee Invitation"),
                ],
                max_length=20,
            ),
        ),
    ]
