"""Permission level constants shared by platform and tenant RBAC."""

PERMISSION_LEVEL_NONE = "none"
PERMISSION_LEVEL_VIEW = "view"
PERMISSION_LEVEL_EDIT = "edit"
PERMISSION_LEVEL_FULL = "full"

PERMISSION_LEVEL_CHOICES = [
    (PERMISSION_LEVEL_NONE, "None"),
    (PERMISSION_LEVEL_VIEW, "View"),
    (PERMISSION_LEVEL_EDIT, "Edit"),
    (PERMISSION_LEVEL_FULL, "Full"),
]

PERMISSION_HIERARCHY = {
    PERMISSION_LEVEL_NONE: 0,
    PERMISSION_LEVEL_VIEW: 1,
    PERMISSION_LEVEL_EDIT: 2,
    PERMISSION_LEVEL_FULL: 3,
}
