# Generated by Django 6.0.6 on 2026-06-29 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0003_alter_branch_options_branch_address_branch_capacity_and_more"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stocklevel",
            name="uniq_stock_level_location_product_variant",
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location_type", "branch")),
                fields=("branch", "product", "variant"),
                name="uniq_branch_stock_product_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location_type", "warehouse")),
                fields=("warehouse", "product", "variant"),
                name="uniq_warehouse_stock_product_variant",
            ),
        ),
    ]
